// the facts to be read out by Alexa, facts are written in chronological order according the order of lectures
module.exports.data = [
    'Youngs double-slit experiment was strong evidence for the wave nature of light.’, ‘The wave nature of light can be described using a Mach-Zehnder Interferometer.’, ‘Plancks experiment implied that light behaved in discrete packets of energy.’, ‘Measurement has a direct effect on the measured system. The photon behaves like a wave when not measured, but behaves like a particle when measured.',
    'For principal quantum numbers, n, the first four series for the spectrum of the Hydrogen atom are Lyman, Balmer, Paschen, Brackett.',
    'De Broglie stated matter should exhibit wave-particle duality, just like photons.',
    'To observe double-slit interference effects, slit separation must be approximately the same size as the wavelength. Human scale objects have tiny de Broglie wavelengths, so their interference effects are never observed.',
    'In a Youngs slit experiment with matter, there is wave-like behaviour while unobserved, and particle-like behaviour when detected.',
    'The wavefunction for a particle is the quantum mechanical representation of the particles position. It can be a positive, negative or complex function.',
    'The integral of the square modulus of the wavefunction between two points gives the probability of finding the particle between two such points.',
    'Wavefunctions must be continuous; there cannot be jumps. This ensures that the first derivative of the wavefunction is finite. Wavefunctions must also be continuous in their first derivative; there cannot be kinks. This ensures that the second derivative is finite.',
    'Expectation values can be calculated by computing the integral of the product of position and the square modulus of the wavefunction, between negative infinity and positive infinity.',
    'When we solve the Time-Independent Schrödinger Equation, we recover the allowed energy eigenvalues and the wavefunctions, or eigenfunctions.',
    'Particles with half-integer spin are called Fermions, and particles with integer spin are called Bosons. The electron is a Fermion with spin-half, and the photon is a Boson with spin-zero.',
    'The Pauli Exclusion Principle states that no two Fermions may inhabit the same quantum state.',
    'Surfaces of stars emit very closely to a black body spectrum, and hence can be modelled as black bodies. These are bodies that absorb all radiation that is incident upon it.',
    'Wiens displacement law expresses the wavelength at which the maximum intensity of blackbody radiation is emitted as a function of temperature.',
    'The Stefan-Boltzmann Law describes how hotter and larger stars emit more flux and light.',
    'The best example of a black body is provided by the spectrum of the microwave background, the relic of the Big Bang, now known to be 2.7 Kelvin.',
    'An emission line is produced when an electron in an excited state falls by one or more levels.',
    'Sources of absorption lines include: stellar atmospheres, interstellar gases, intergalactic Lyman-alpha systems of clouds at different redshifts.',
    'When the observed wavelength is larger than the emitted wavelength, there is redshift and the emitter is moving away from the observer. Blueshift occurs when the observed wavelength is smaller than the emitted wavelength, and the emitter is moving towards the observer.',
    'Hot stars are blue, whilst cool stars are red. Intermediate stars are yellow.',
    'Luminosity classes are designated by Roman Numerals. 1a are the most luminous supergiants, 1b are the supergiants, 2 are the luminous giants, 3 are the giants, 4 are the subgiants, 5 are the main sequence stars.',
    'A star is said to be in hydrostatic equilibrium if only the inward gravitational force and the outward thermal pressure are at work in the gas.',
    'Nuclear fusion is the process by which small nuclei of atoms are joined into larger ones, generating vast energy.',
    'Nuclear fission is the process by which a heavy nuclei of an atom breaks up into lighter nuclei of different atoms, releasing large amounts of energy.',
    'The mass deficit is defined as the nuclear binding energy that holds the nucleus together.',
    'The neutrinos in the PP1, PP2 and PP3 chains carry away 2.0 percent, 4.0 percent and 28.3 percent of the energy respectively.',
    'Nuclear fusion produces only electron-neutrinos, whilst laboratory accelerators and exploding stars can produce muon-neutrions and tau-neutrinos.',
    'The general sequence of stellar evolution is as follows: protostar, pre-main sequence, main sequence, post-main sequence. An evolutionary track is a plot of points showing the time sequence of evolutionary stages of a star on an H-R diagram.',
    '90 percent of stars lie on the main sequence, where stars burning Hydrogen and Helium are in hydrostatic equilibrium.',
    'Stars are born from huge interstellar clouds of gas and dust, which are massive enough to contract gravitationally. Collapse starts in free-fall. Particles do not collide, meaning there is no internal pressure, and it is a protostar.',
    'As density increases, the clouds core traps infra-red radiation from dust heated by collisions with molecules, and collapse slows down, establishing hydrostatic equilibrium. This is the pre-main sequence star.',
    'The pre-main sequence star shines by slowly contracting, while matter accretes onto its core and the central temperature rises. As this temperature is high enough to start Hydrogen burning, collapse halts and the star is now a main-sequence star.',
    'Evolution is faster for more massive stars, as these have higher central temperatures, meaning nuclear reactions occur faster.',
    'As the mass of a white dwarf star increases, the radius decreases. The Chandrasekhar limit of 1.44 solar masses defines the ultimate mass limit for white dwarf stars.',
    'Neutron stars of a mass larger than three solar masses are unstable against further collapse to a black hole.',
    'A black hole is a body that is all contained within its Schwarzschild radius, which is the critical radius where the escape velocity equals the speed of light. It is also known as the event horizon, and nothing can escape.',
    'Elliptical galaxies are pure bulge and have no disk component. Spiral galaxies contain varying amounts of disk component. Irregular galaxies do not have a set of rules.',
    'Elliptical galaxies are classified by measuring their major and minor axes. E0 is round and E6 is elongated.',
    'Spiral galaxies are classified in order of decreasing bulge to disk ratio as S-a, S-b and S-c. Barred spiral galaxies are called S-B-a, S-B-b and S-B-c.',
    'Elliptical galaxies are spheroidal systems with little or no rotation, whereas spiral galaxies are flattened systems that rotate.',
    'In elliptical galaxies, orbits of stars are randomly oriented and highly eccentric, whereas the orbits of stars and gas are circular in spiral galaxies, rotating about the disk axis.',
    'In elliptical galaxies, star formation is largely complete as gas was consumed efficiently a long time ago. Star formation is on-going in spiral galaxies.',
    'Ages of stars in elliptical galaxies are mainly old, whereas they vary from the age of the galaxy to new, in spiral galaxies.',
    'There is very little gas in elliptical galaxies as most of it has been converted to stars already. For spiral galaxies, the gas and dust mass fraction is roughly 10 to 50 percent of the full disk.',
    'Overall structure of elliptical galaxies is smooth, whereas there are spiral arms that are sustained as density waves in spiral galaxies.',
    'Population 1 stars contain lots of metal, are young and blue, and have circular orbits. Blue disk stars are Population 1.',
    'Population 2 stars are metal-poor, old and red, and have elliptical and tilted orbits. Red bulge and halo stars are Population 2.',
    'Hubbles law states that the further away a galaxy is, the greater its redshift.',
    'Type 1a Supernovae have become the principal distance indicator for determination of distances on cosmological scales.',
    'According to the Hot Big Bang Theory, the Universe began at a finite time in the past, as an incredibly hot and dense fireball, which has been expanding and cooling ever since.',
    'Evidence for the Big Bang can be found in: the expansion of the Universe, the evolution of the Universe, the cosmic microwave background radiation, or CMBR, and the abundances of the lightest chemical elements.',
    'Knowing the current rate of expansion of the Universe we can estimate the time it took for galaxies to move as far apart as they are today, giving an age of the universe of 13.8 billion years.',
    'From about 20 minutes after the Big Bang, the abundances have remained constant. The Universe was too cool after this period of time for any more cooking of elements, and there were not enough high-energy photons to blast apart the elements already formed.',
    'Homogeneity states that, on the largest scales, the local Universe has the same physical properties throughout the Universe.',
    'Isotropy states that, on the largest scales, the local Universe looks the same in an direction that one observes.',
    'Universality states that the laws of physics are the same everywhere in the Universe.',
    'The critical density is defined as the density that is just enough to slow the cosmic expansion to a halt at infinity.',
    'If the density of matter was greater than the critical density, the Universe will collapse back. The Universe will be flat if the density of matter equals the critical density. The Universe will expand forever if the density of matter is less than the critical density.',
    'Unexpectedly, SN 1a measurements showed that the universe is accelerating.',
];